#!/usr/bin/env python

import sys

from can_bus_gui.canbus_dashboard_module import Canbus_Dashboard_Plugin
from rqt_gui.main import Main

plugin = 'can_bus_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
