#!/usr/bin/env python

import sys

from can_bus_gui.controller_status_module import ControllerStatusPlugin
from rqt_gui.main import Main

plugin = 'controller_status_widget'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
